framework:
    secret: S0ME_SECRET
    profiler: { only_exceptions: false }

knp_snappy:  
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64